spring:
  profiles:
    active: test
---
spring:
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:33061/tdd?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    cache: false
  redis:
    database: 0
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3000
        min-idle: 2
    timeout: 3000
    host: localhost
    port: 16379
    password: 123456

server:
  port: 8080

logging:
  level:
    com.imzhizi.tdd: debug

mybatis:
  type-aliases-package: com.imzhizi.tdd.domain.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

salt: "keep_my_secret"